version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  celery:
    build:
      context: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env


  wkhtmltopdf:
    image: "openlabs/docker-wkhtmltopdf:latest"

volumes:
  postgres_data:
